
-- -- 1
-- CREATE USER usuario_01;

-- SELECT * FROM mysql.user;

-- GRANT SELECT ON *.* TO usuario_01;

-- -- 2

-- CREATE USER usuario_02;

-- GRANT SELECT,DELETE,UPDATE,INSERT ON KIROLDENDA.* TO usuario_02;

-- -- 3
-- CREATE USER usuario_03;

-- GRANT SELECT,UPDATE ON KIROLDENDA.empleados TO usuario_03;

-- -- 4
-- CREATE USER usuario_04;

-- GRANT SELECT ON KIROLDENDA.articulos TO usuario_04;
-- GRANT SELECT ON KIROLDENDA.categorias TO usuario_04;
-- GRANT SELECT ON KIROLDENDA.clientes TO usuario_04;
-- GRANT SELECT ON KIROLDENDA.departamentos TO usuario_04;
-- GRANT SELECT ON KIROLDENDA.lineas TO usuario_04;
-- GRANT SELECT ON KIROLDENDA.pedidos TO usuario_04;
-- GRANT SELECT (empleadoID,nombre,puesto,jefe,fnac,comision,departamentoID) ON KIROLDENDA.empleados TO usuario_04;

-- -- 5

-- CREATE USER usuario_05 IDENTIFIED BY 'password';
-- GRANT SELECT,DELETE,UPDATE,INSERT ON KIROLDENDA.* TO usuario_05;
-- GRANT CREATE ON KIROLDENDA.* TO usuario_05;

-- -- 6

-- CREATE USER usuario_99 IDENTIFIED BY 'password';
-- GRANT SELECT,DELETE,UPDATE,INSERT ON KIROLDENDA.* TO usuario_99;
-- GRANT SHUTDOWN ON *.* TO usuario_99;

-- -- 7
-- CREATE USER admin1 IDENTIFIED BY 'password';
-- GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, ALTER, INDEX, EXECUTE, SHOW VIEW, CREATE VIEW, TRIGGER, CREATE ROUTINE, ALTER ROUTINE, EVENT, FILE, RELOAD, SHUTDOWN, PROCESS, REFERENCES ON *.* TO 'admin1';

-- 8 
-- CREATE USER admin99 IDENTIFIED BY 'password';
-- GRANT ALL PRIVILEGES ON *.* TO admin99 WITH GRANT OPTION;